version: '3.3'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            TZ: 'AMERICA/SAO_PAULO'
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        expose:
            - '3306'
        volumes:
            - './src/database/structure.sql:/docker-entrypoint-initdb.d/1.sql'
        networks:
            - back
    api:
        build: .
        restart: unless-stopped
        links:
            - "db"
        ports:
            - "3000:3000"
        networks:
            - back
    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        restart: unless-stopped
        links:
            - "db"
        environment:
            - TZ=America/Sao_Paulo
            - PMA_HOST=db
            - PMA_PORT=3306
            - UPLOAD_LIMIT=100M
        networks:
            - back

networks:
    back:
        driver: bridge
